namespace DeviceInterface.Dmst;

/// <summary>
/// Fields extracted from a DMST TruCheck HTML report for one scan.
///
/// The DMST HTML report is generated by the DataMan Setup Tool after every
/// verification scan and displayed in the TruCheck report tab. It is the
/// firmware's own rendering of the result and is authoritative for fields
/// that are not exposed through the push script's JS scope.
///
/// Source routing:
///   Push XML fields  → DmstResultParser   → VerificationRecord (primary)
///   HTML-only fields → DmstHtmlScraper    → VerificationRecord (supplemental,
///                                            flagged in DataSourceExceptions)
///   Overlapping fields are cross-validated by DmstReportValidator.
///
/// NOTE: The actual HTML format has not yet been sampled. Field names and
/// CSS/XPath selectors are placeholders — update after first live HTML capture.
/// See session_plan.md: "HTML Report Scraping &amp; Cross-Validation" for status.
/// </summary>
public sealed class DmstHtmlReport
{
    // ── Correlation ───────────────────────────────────────────────────────────

    /// <summary>
    /// Scan timestamp from the report header. Used to correlate this HTML report
    /// with the corresponding push XML VerificationRecord (±2s tolerance).
    /// </summary>
    public DateTime? ScanDateTime { get; init; }

    // ── Fields absent from push XML on fw 6.1.16_sr4 (primary targets) ───────

    /// <summary>
    /// QR Error Correction Level: L / M / Q / H.
    /// Not exposed through push script JS scope — sourced from HTML report only.
    /// Maps to VerificationRecord.QR_ECLevel.
    /// </summary>
    public string? ECLevel { get; init; }

    /// <summary>
    /// QR Data Mask Pattern number (0–7).
    /// Not exposed through push script JS scope — sourced from HTML report only.
    /// Maps to VerificationRecord.QR_MaskPattern.
    /// </summary>
    public string? DataMaskPattern { get; init; }

    /// <summary>
    /// ECI (Extended Channel Interpretation) value, e.g. "000003" (Latin-1).
    /// Not exposed through push script JS scope — sourced from HTML report only.
    /// Maps to VerificationRecord.QR_ECI.
    /// </summary>
    public string? ECI { get; init; }

    /// <summary>
    /// Image polarity string as shown in DMST report: "Normal" or "Inverted".
    /// Not exposed through push script JS scope — sourced from HTML report only.
    /// Maps to VerificationRecord.ImagePolarity (enum: BlackOnWhite / WhiteOnBlack).
    /// </summary>
    public string? ImagePolarity { get; init; }

    // ── Fields present in BOTH push XML and HTML (cross-validation targets) ───

    /// <summary>Overall verification grade letter (A/B/C/D/F).</summary>
    public string? OverallGrade { get; init; }

    /// <summary>Decoded data string.</summary>
    public string? DecodedData { get; init; }

    /// <summary>Symbology name as shown in report (e.g. "Data Matrix", "QR Code").</summary>
    public string? SymbologyName { get; init; }

    /// <summary>
    /// Matrix dimensions string (e.g. "16x36", "29x29").
    /// HTML may show "16 x 36" with spaces — normalise on compare.
    /// </summary>
    public string? MatrixSize { get; init; }

    /// <summary>
    /// Nominal X Dimension as shown in report (e.g. "12.6 mil").
    /// Stored as raw string to preserve units for direct comparison with push XML.
    /// </summary>
    public string? NominalXDim { get; init; }

    /// <summary>
    /// ContrastUniformity as shown in report (e.g. "72 at module(10,5)").
    /// Stored as string because the HTML may show the full annotated form.
    /// </summary>
    public string? ContrastUniformity { get; init; }

    /// <summary>
    /// Minimum Reflectance Difference as shown in report (e.g. "71% (77% - 6%)").
    /// Stored as string because the HTML includes the component breakdown.
    /// </summary>
    public string? MRD { get; init; }

    /// <summary>Horizontal Bar Width Growth percentage (numeric).</summary>
    public decimal? HorizontalBWG { get; init; }

    /// <summary>Vertical Bar Width Growth percentage (numeric).</summary>
    public decimal? VerticalBWG { get; init; }

    /// <summary>Axial Non-Uniformity percentage (numeric, e.g. 0.84).</summary>
    public decimal? ANUPercent { get; init; }

    /// <summary>Grid Non-Uniformity percentage (numeric).</summary>
    public decimal? GNUPercent { get; init; }

    /// <summary>Unused Error Correction percentage (numeric, 0–100).</summary>
    public decimal? UECPercent { get; init; }

    /// <summary>Symbol Contrast percentage (numeric).</summary>
    public decimal? SCPercent { get; init; }

    /// <summary>Fixed Pattern Damage value (numeric).</summary>
    public decimal? FPDValue { get; init; }

    /// <summary>Error Correction Type string (e.g. "ECC200"; for QR: "L"/"M"/"Q"/"H").</summary>
    public string? ErrorCorrectionType { get; init; }

    /// <summary>Individual scan grade metrics keyed by metric name (e.g. "UEC" → "A").</summary>
    public IReadOnlyDictionary<string, string> GradeMetrics { get; init; }
        = new Dictionary<string, string>();

    // ── Parse provenance ──────────────────────────────────────────────────────

    /// <summary>
    /// Path to the HTML file this report was parsed from.
    /// Retained for diagnostics; file is deleted after parsing.
    /// </summary>
    public string? SourceFilePath { get; init; }

    /// <summary>
    /// True if the HTML was successfully parsed and at least ScanDateTime was found.
    /// False if the parser encountered an unrecognised format.
    /// </summary>
    public bool ParseSucceeded { get; init; }

    /// <summary>Parser error message, or null if parsing succeeded.</summary>
    public string? ParseError { get; init; }
}
